export const MCP_ENV = {
  WORKSPACE_ROOT: "MCP_WORKSPACE_ROOT",
  PROBE_BASE_URL: "MCP_PROBE_BASE_URL",
  PROBE_STATUS_PATH: "MCP_PROBE_STATUS_PATH",
  PROBE_RESET_PATH: "MCP_PROBE_RESET_PATH",
  PROBE_WAIT_MAX_RETRIES: "MCP_PROBE_WAIT_MAX_RETRIES",
  RECIPE_OUTPUT_TEMPLATE: "MCP_RECIPE_OUTPUT_TEMPLATE",
  AUTH_LOGIN_DISCOVERY_ENABLED: "MCP_AUTH_LOGIN_DISCOVERY_ENABLED",
} as const;

export type McpEnvVar = (typeof MCP_ENV)[keyof typeof MCP_ENV];
