export const MCP_ENV = {
  WORKSPACE_ROOT: "MCP_WORKSPACE_ROOT",
  PROBE_BASE_URL: "MCP_PROBE_BASE_URL",
  PROBE_LINE_SELECTION_MAX_SCAN_LINES: "MCP_PROBE_LINE_SELECTION_MAX_SCAN_LINES",
  PROBE_INCLUDE_EXECUTION_PATHS: "MCP_PROBE_INCLUDE_EXECUTION_PATHS",
  PROBE_WAIT_MAX_RETRIES: "MCP_PROBE_WAIT_MAX_RETRIES",
  PROBE_WAIT_UNREACHABLE_RETRY_ENABLED: "MCP_PROBE_WAIT_UNREACHABLE_RETRY_ENABLED",
  PROBE_WAIT_UNREACHABLE_MAX_RETRIES: "MCP_PROBE_WAIT_UNREACHABLE_MAX_RETRIES",
} as const;

export type McpEnvVar = (typeof MCP_ENV)[keyof typeof MCP_ENV];
